spring:
  application:
    name: inventory-sync
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/inventory-sync
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none