name: Publish

on:
  push:
    branches:
      - publish

permissions:
  packages: write

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: 21
            cache: 'maven'
      - name: Package with Maven
        run: mvn package
      - name: Build and publish docker image
        uses: VaultVulp/gp-docker-action@1.6.0
        with:
          dockerfile: Dockerfile
          image-name: inventory-sync-service
          image-tag: 'latest'
          github-token: ${{secrets.GITHUB_TOKEN}}
          custom-args: --platform=linux/arm64,linux/amd64
